version: "3.3"
    
services:
  workermanager:
    container_name: cluster_manager
    image: pigeatgarlic/workermanager:development
    environment:
      REDIS_IP: "cache"
    restart: unless-stopped
    ports:
      - "5000:80"

  cluster-ui:
    container_name: cluster_ui
    image: pigeatgarlic/cluster-ui:2022-01-03
    restart: unless-stopped
    ports:
      - "8080:3000"

  cache:
    container_name: redis_cache
    image: redis:latest
    volumes:
       - /home/cache:/data
    restart: unless-stopped