FROM pigeatgarlic/gstreamer-base:1.19.2 

WORKDIR /source

# debugging tool
RUN \
    apt install -y libsoup-gnome2.4-dev \
                   libjson-glib-1.0-0 \
                   libjson-glib-dev \
                   libx11-dev \
                   xserver-xorg-dev \
                   xorg-dev \
                   libgtkmm-3.0-dev \
                   libgstreamermm-1.0-dev \
                   gdb  \
                   cmake



CMD sleep 6000m 


